# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management
    username: root
    password: root
  # JPA properties
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
# Server configuration
server:
  port: 8083
# Security configuration
security:
  user:
    name: user
password: user